### PR TITLE
change blob type to text/javascript

### PR DESCRIPTION
**Pull request by DerKorb**
hopefully prevents "Uncaught (in promise) DOMException: The user aborted a request."
according to https://bugs.chromium.org/p/chromium/issues/detail?id=807160

### CODE REVIEW

**Comment by chrisguttandin** [comment]
Hi @DerKorb, many thanks for your pull request.

I'm wondering if the changes that you made actually solve the problem? The code you modified deals with an ObjectURL and the bug that you referenced is caused by a DataURL. I would assume that it will still fail to load a given DataURL as that is done before: https://github.com/DerKorb/standardized-audio-context/blob/454406f58329f6ae67634f22d311aac847ce4aa8/src/add-audio-worklet-module.ts#L42

**Comment by DerKorb** [comment]
I finally managed to test it and it does not fix the error. Does your code work for you in recent chrome builds?

**Comment by chrisguttandin** [comment]
Thanks for verifying that. We could however replace the "data:..." beginning in case someone uses a data URL. I will give that a try later today.

Despite the "text/javascript" and "application/javascript" bug everything should be working in the latest Chrome. However there is a little bug/feature (I don't know yet what it is) in Chrome Canary which currently prevents the tests from running.

**Comment by chrisguttandin** [comment]
hi @DerKorb, I spent some time today reading about the issues with DataURLs and I think it is best to not implement a fix as part of this package. It seems to me that it is outside of the scope of the Web Audio API.

And besides that it is always possible to convert a DataURL into an ObjectURL on the fly.

Nevertheless many thanks for reporting this. Let me know if you run into other issues.

**Pull request closed without merging**
